# Generated by Django 3.0.9 on 2021-03-25 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='student_id',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='assessment',
            name='q33_answer',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='q34_answer',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='q35_answer',
            field=models.CharField(max_length=200),
        ),
    ]
