# Generated by Django 3.0.9 on 2021-03-16 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0005_auto_20201030_1734'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postassessment',
            name='q23_score',
        ),
        migrations.RemoveField(
            model_name='postassessment',
            name='q24_score',
        ),
        migrations.RemoveField(
            model_name='postassessment',
            name='q25_score',
        ),
        migrations.RemoveField(
            model_name='postassessment',
            name='q26_score',
        ),
        migrations.RemoveField(
            model_name='postassessment',
            name='q27_score',
        ),
        migrations.RemoveField(
            model_name='postassessment',
            name='q28_score',
        ),
        migrations.RemoveField(
            model_name='postassessment',
            name='q29_score',
        ),
        migrations.RemoveField(
            model_name='postassessment',
            name='q30_score',
        ),
        migrations.RemoveField(
            model_name='postassessment',
            name='q31_score',
        ),
        migrations.RemoveField(
            model_name='postassessment',
            name='q32_score',
        ),
        migrations.RemoveField(
            model_name='postassessment',
            name='q33_score',
        ),
        migrations.RemoveField(
            model_name='postassessment',
            name='q34_score',
        ),
        migrations.RemoveField(
            model_name='postassessment',
            name='q35_score',
        ),
        migrations.RemoveField(
            model_name='preassessment',
            name='q23_score',
        ),
        migrations.RemoveField(
            model_name='preassessment',
            name='q24_score',
        ),
        migrations.RemoveField(
            model_name='preassessment',
            name='q25_score',
        ),
        migrations.RemoveField(
            model_name='preassessment',
            name='q26_score',
        ),
        migrations.RemoveField(
            model_name='preassessment',
            name='q27_score',
        ),
        migrations.RemoveField(
            model_name='preassessment',
            name='q28_score',
        ),
        migrations.RemoveField(
            model_name='preassessment',
            name='q29_score',
        ),
        migrations.RemoveField(
            model_name='preassessment',
            name='q30_score',
        ),
        migrations.RemoveField(
            model_name='preassessment',
            name='q31_score',
        ),
        migrations.RemoveField(
            model_name='preassessment',
            name='q32_score',
        ),
    ]
