# Generated by Django 3.0.9 on 2021-04-23 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='q23_answer',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='q24_answer',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='q25_answer',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='q26_answer',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='q27_answer',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='q28_answer',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='q29_answer',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='q30_answer',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='q31_answer',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='q32_answer',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='q33_answer',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='q34_answer',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='q35_answer',
            field=models.IntegerField(),
        ),
    ]
